# Generated by Django 4.2.11 on 2024-08-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='actors',
            field=models.TextField(default=1234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.TextField(default=1234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='trailer',
            field=models.URLField(default=1235),
            preserve_default=False,
        ),
    ]
