# Generated by Django 4.2.11 on 2024-08-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0002_rename_name_category_title_rename_name_product_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='username',
            field=models.CharField(default=1234, max_length=200),
            preserve_default=False,
        ),
    ]
