# Generated by Django 4.2.11 on 2024-08-06 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0004_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
