# Generated by Django 4.2.11 on 2024-08-07 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0006_registration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Movie',
        ),
    ]
