# Generated by Django 4.2.11 on 2024-08-07 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0007_rename_product_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
